baseURL = 'https://tribune242.com/'
languageCode = 'en-us'
title = 'The Tribune'

[taxonomies]
  category = "categories"
  subcategory = "subcategories"

[sass]
  use_dart_sass = true

upload_dir = "assets/uploads"
public_path = "/uploads"
# disableKinds = [ "taxonomy", "term" ]

[ params ]
  version = "1738220434631"
  twic = "jsphpndr"
  share = "/uploads/joseph-pinder-share.jpg"
  logo = "/uploads/joseph-pinder-logo.png"
  # Facebook App ID
  app_id = "223848628924279"
  error = true

  [params.social]
    facebook = "jsphpndr"
    instagram = "jsphpndr"
    linkedin = "jsphpndr"
    github = "jsphpndr"
    x = "jsphpndr"

[markup]
  [markup.goldmark]
    [markup.goldmark.parser]
      wrapStandAloneImageWithinParagraph = false
      [markup.goldmark.parser.attribute]
        block = true

    # Links
    [markup.goldmark.renderHooks]
      [markup.goldmark.renderHooks.link]
        enableDefault = true        

enableGitInfo = true

[sitemap]
  filename = "sitemap"  # Remove .xml
  changefreq = "monthly"
  priority = 0.5
